<a href="https://colab.research.google.com/github/nxn0/nxn0/blob/main/kfoldCrossVal_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np


In [36]:
from sklearn.datasets import load_iris
iris = load_iris()

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split


In [38]:
x = iris.data
y = iris.target

In [75]:
lrmodel = LogisticRegression()
dtmodel = DecisionTreeClassifier()
rfmodel = RandomForestClassifier()
svmmodel = SVC()

In [76]:
from sklearn.model_selection import cross_val_score

In [77]:
cross_val_score(lrmodel,x,y )

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [78]:
np.average (cross_val_score(lrmodel,x,y))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9733333333333334

In [79]:
cross_val_score(dtmodel,x,y)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [80]:
np.average (cross_val_score(dtmodel,x,y))

0.9666666666666668

In [81]:
cross_val_score(rfmodel,x,y)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [82]:
np.average (cross_val_score(rfmodel,x,y))

0.9533333333333334

In [83]:
cross_val_score(svmmodel,x,y)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [84]:
np.average (cross_val_score(svmmodel,x,y))


0.9666666666666666