<a href="https://colab.research.google.com/github/nxn0/nxn0/blob/main/kforestdigit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [7]:
x = digits.data
y = digits.target

In [16]:
lrmodel = LogisticRegression(max_iter=2000)
rfmodel = RandomForestClassifier(n_estimators=200)
svmmodel = SVC()


In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(lrmodel,x,y)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [19]:
cross_val_score(rfmodel,x,y)

array([0.93611111, 0.91944444, 0.9637883 , 0.96100279, 0.92200557])

In [20]:
cross_val_score(svmmodel,x,y)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [21]:
np.average(cross_val_score(lrmodel,x,y))

0.9148777468276075

In [22]:
np.average(cross_val_score(rfmodel,x,y))

0.942143299288146

In [23]:
np.average(cross_val_score(svmmodel,x,y))

0.9632838130609718